### ISSUE TITLE
Problem with decorator

### ISSUE THREAD

**Issue by NewDay1313** [Neoteroi/BlackSheep#155]
```
from blacksheep.server.controllers import Controller, get, post
from blacksheep.cookies import Cookie
from blacksheep.messages import Response
from easy_cryptography.hash.hash_funct import compare_hash
from app.configuration import AUTHORIZED
from models import Doctors
from pony.orm import *

class Home(Controller):
    
    @get("/")
    def index(self):
        return self.view()

class Patients(Controller):

    @get("/patients")
    def patients(self, login: str, password: str):
        if Doctors.exists(login) and (compare_hash(password, Doctors.get_for_update(login = login).password)):
            patients = Patients.select()
            response = self.view(patients=patients)
            response.set_cookie(Cookie(AUTHORIZED,True))
            return response
        else:    
            return "{'message':'Неверный логин или пароль'}"
```

I got this error

Traceback (most recent call last):
  File "c:\program files\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\program files\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python38\Scripts\uvicorn.exe\__main__.py", line 7, in <module>
  File "c:\program files\python38\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\program files\python38\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\program files\python38\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\program files\python38\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\program files\python38\lib\site-packages\uvicorn\main.py", line 362, in main
    run(**kwargs)
  File "c:\program files\python38\lib\site-packages\uvicorn\main.py", line 386, in run
    server.run()
  File "c:\program files\python38\lib\site-packages\uvicorn\server.py", line 49, in run
    loop.run_until_complete(self.serve(sockets=sockets))
  File "c:\program files\python38\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "c:\program files\python38\lib\site-packages\uvicorn\server.py", line 56, in serve
    config.load()
  File "c:\program files\python38\lib\site-packages\uvicorn\config.py", line 308, in load
    self.loaded_app = import_from_string(self.app)
  File "c:\program files\python38\lib\site-packages\uvicorn\importer.py", line 20, in import_from_string
    module = importlib.import_module(module_str)
  File "c:\program files\python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\1\Desktop\Avicena\.\server.py", line 14, in <module>
    from app.program import configure_application
  File "C:\Users\1\Desktop\Avicena\.\app\program.py", line 7, in <module>
    from . import controllers  # NoQA
  File "C:\Users\1\Desktop\Avicena\.\app\controllers\__init__.py", line 1, in <module>
    from .home import Home, Patients
  File "C:\Users\1\Desktop\Avicena\.\app\controllers\home.py", line 9, in <module>
    class Home(Controller):
  File "C:\Users\1\Desktop\Avicena\.\app\controllers\home.py", line 11, in Home
    @get("/")
  File "c:\program files\python38\lib\site-packages\pony\orm\core.py", line 5587, in get
    return make_query(args, frame_depth=cut_traceback_depth+1).get()
  File "c:\program files\python38\lib\site-packages\pony\orm\core.py", line 5569, in make_query
    tree = string2ast(gen)
  File "c:\program files\python38\lib\site-packages\pony\orm\core.py", line 5516, in string2ast
    module_node = parse('(%s)' % s)
  File "c:\program files\python38\lib\site-packages\pony\thirdparty\compiler\transformer.py", line 64, in parse
    return Transformer().parsesuite(buf)
  File "c:\program files\python38\lib\site-packages\pony\thirdparty\compiler\transformer.py", line 165, in parsesuite
    return self.transform(parser.suite(text))
  File "<string>", line 1
    (/)
     ^
SyntaxError: invalid syntax

**Comment by NewDay1313** [comment]
It was problem with orm
