### ISSUE TITLE
Running MVC Tutorial not possible -- ModuleNotFoundError: No module named 'pkg_resources'

### ISSUE THREAD

**Issue by legout** [Neoteroi/BlackSheep#377]
I´ve tried to run the tutorial "Getting started with the MVC project template". Therefore I´ve cloned the repo, created a new venv (python 3.10) installed the deps.
When running `./start.sh` I get the following error:

```
❯ ./start.sh 
INFO:     Will watch for changes in these directories: ['/home/ubuntu/Projects/00__Playground/blacksheep/BlackSheepMVC']
INFO:     Uvicorn running on http://127.0.0.1:44777 (Press CTRL+C to quit)
INFO:     Started reloader process [121323] using StatReload
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/home/ubuntu/mambaforge/envs/base3.10/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/ubuntu/mambaforge/envs/base3.10/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/Projects/00__Playground/blacksheep/BlackSheepMVC/.venv/lib/python3.10/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/ubuntu/Projects/00__Playground/blacksheep/BlackSheepMVC/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/home/ubuntu/mambaforge/envs/base3.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/home/ubuntu/Projects/00__Playground/blacksheep/BlackSheepMVC/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/home/ubuntu/Projects/00__Playground/blacksheep/BlackSheepMVC/.venv/lib/python3.10/site-packages/uvicorn/config.py", line 473, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/ubuntu/Projects/00__Playground/blacksheep/BlackSheepMVC/.venv/lib/python3.10/site-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/home/ubuntu/Projects/00__Playground/blacksheep/BlackSheepMVC/.venv/lib/python3.10/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/home/ubuntu/mambaforge/envs/base3.10/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubuntu/Projects/00__Playground/blacksheep/BlackSheepMVC/server.py", line 14, in <module>
    from app.program import configure_application
  File "/home/ubuntu/Projects/00__Playground/blacksheep/BlackSheepMVC/app/program.py", line 4, in <module>
    from blacksheep.server import Application
  File "/home/ubuntu/Projects/00__Playground/blacksheep/BlackSheepMVC/.venv/lib/python3.10/site-packages/blacksheep/__init__.py", line 28, in <module>
    from .server.application import Application as Application
  File "/home/ubuntu/Projects/00__Playground/blacksheep/BlackSheepMVC/.venv/lib/python3.10/site-packages/blacksheep/server/__init__.py", line 1, in <module>
    from .application import Application as Application
  File "/home/ubuntu/Projects/00__Playground/blacksheep/BlackSheepMVC/.venv/lib/python3.10/site-packages/blacksheep/server/application.py", line 46, in <module>
    from blacksheep.server.errors import ServerErrorDetailsHandler
  File "/home/ubuntu/Projects/00__Playground/blacksheep/BlackSheepMVC/.venv/lib/python3.10/site-packages/blacksheep/server/errors.py", line 7, in <module>
    from blacksheep.server.resources import get_resource_file_content
  File "/home/ubuntu/Projects/00__Playground/blacksheep/BlackSheepMVC/.venv/lib/python3.10/site-packages/blacksheep/server/resources.py", line 3, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'```

**Comment by RobertoPrevato** [comment]
Hi @legout 
Thank You for creating this issue. I needed to do some maintenance. Even though I pinned the dependencies there, some non backward compatible changes in pip in the last months required updating some dependencies.

Please try again, I updated the project template to use the latest versions of packages and verified it works again. I used Python 3.11 to test.
