### ISSUE TITLE
ConnectionResetError keeps happening

### ISSUE THREAD

**Issue by remdragon** [Neoteroi/BlackSheep#401]
Keep getting these on the console. Is there something that I have misconfigured?

```
Jul17 08:42:20.333 CDT-0500 <18064> [asyncio] ERROR: Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Python310-64\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Python310-64\lib\asyncio\proactor_events.py", line 165, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
```

This happens regardless of whether I have a valid cert or a self-signed cert.

Here's how my environment is boot-strapped, in case it matters:

```
	uvicorn.run(
		'__main__:app',
		host = http_interface,
		port = http_port,
		log_level = 'info',
		workers = 1,
		ssl_keyfile = str( cert.key_path ),
		ssl_certfile = cert.crt_path,
	)
```

Version information:
```
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)] on win32
blacksheep==1.2.18
uvicorn==0.23.0
```

**Comment by RobertoPrevato** [comment]
Sorry for not following up on this issue back when it was opened. I never experienced this error while working with the framework. I am closing this issue now. If anything similar still happens a new issue can be opened.
