### ISSUE TITLE
Handled exception is logged as unhandled

### ISSUE THREAD

**Issue by mohd-akram** [Neoteroi/BlackSheep#421]
**Describe the bug**

Blacksheep erroneously logs an error saying that an exception is unhandled despite it being handled:

```python
from blacksheep.server import Application

app = Application()

@app.router.get('/type-error')
async def type_error():
    raise TypeError()

@app.exception_handler(Exception)
async def handler(self, request, exception):
    print('caught', exception.__class__.__name__)
```

`curl localhost:8000/type-error`:

```python
Unhandled exception - "GET /type-error"
Traceback (most recent call last):
  File "blacksheep/baseapp.pyx", line 84, in blacksheep.baseapp.BaseApplication.handle
  File "/Users/user/Library/Python/3.11/lib/python/site-packages/blacksheep/server/normalization.py", line 543, in handler
    return ensure_response(await method(request))
                           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/Library/Python/3.11/lib/python/site-packages/blacksheep/server/normalization.py", line 513, in handler
    return await method()
           ^^^^^^^^^^^^^^
  File "/tmp/main.py", line 7, in type_error
    raise TypeError()
TypeError
caught TypeError
```

**Comment by RobertoPrevato** [comment]
Hi @mohd-akram 
Thank You for reporting this issue. I will fix it after I release the documentation for v2 and v2 package as production / stable.
